
package main.java.ru.genereted.v2.fss.integration.ws.eln.mo.v01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import main.java.ru.genereted.v2.types.commom.v01.ObjectFactory;
import main.java.ru.genereted.v2.types.eln.mo.v01.DisableLnRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetExistingLNNumRangeOut;
import main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetLNDataOut;
import main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetLNListByDateOut;
import main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetLNListBySnilsOut;
import main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetNewLNNumOut;
import main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetNewLNNumRangeOut;
import main.java.ru.genereted.v2.types.eln.mo.v01.GetExistingLNNumRangeRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.GetLNDataRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.GetLNListByDateRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.GetLNListBySnilsRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.GetNewLNNumRangeRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.GetNewLNNumRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.PrParseFileNumberslpuRequest;
import main.java.ru.genereted.v2.types.eln.mo.v01.PrParseFilelnlpuRequest;
import main.java.ru.genereted.v2.types.eln.v01.WSResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileOperationsLnService", targetNamespace = "http://www.fss.ru/integration/ws/eln/mo/v01")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    main.java.ru.genereted.v2.types.eln.v01.ObjectFactory.class,
    main.java.ru.genereted.v2.types.eln.mo.v01.ObjectFactory.class,
    ObjectFactory.class,
    main.java.ru.genereted.v2.types.sedo.v01.ObjectFactory.class,
    main.java.ru.genereted.v2.types.fault.v01.ObjectFactory.class,
    main.java.ru.genereted.v2.types.identitydocument.v01.ObjectFactory.class,
    main.java.ru.genereted.v2.types.person.v01.ObjectFactory.class,
    main.java.ru.genereted.v2.types.dic.fault.v01.ObjectFactory.class,
    main.java.ru.genereted.v2.types.dic.errors.v01.ObjectFactory.class
})
public interface FileOperationsLnService {


    /**
     * �������� ������ ���
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.v01.WSResult
     * @throws InternalException
     */
    @WebMethod(operationName = "PrParseFilelnlpu", action = "http://www.fss.ru/integration/ws/eln/mo/prParseFilelnlpu/v01")
    @WebResult(name = "prParseFilelnlpuResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public WSResult prParseFilelnlpu(
        @WebParam(name = "prParseFilelnlpuRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        PrParseFilelnlpuRequest request)
        throws InternalException
    ;

    /**
     * ������� ���������������� ������� ���
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.v01.WSResult
     * @throws InternalException
     */
    @WebMethod(operationName = "PrParseFileNumberslpu", action = "http://www.fss.ru/integration/ws/eln/mo/parseFileNumberslpu/v01")
    @WebResult(name = "prParseFileNumberslpuResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public WSResult prParseFileNumberslpu(
        @WebParam(name = "prParseFileNumberslpuRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        PrParseFileNumberslpuRequest request)
        throws InternalException
    ;

    /**
     * ������ ��� �� ����
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetLNListByDateOut
     * @throws InternalException
     */
    @WebMethod(operationName = "GetLNListByDate", action = "http://www.fss.ru/integration/ws/eln/mo/getLNListByDate/v01")
    @WebResult(name = "getLNListByDateResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public FileOperationsLnUserGetLNListByDateOut getLNListByDate(
        @WebParam(name = "getLNListByDateRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        GetLNListByDateRequest request)
        throws InternalException
    ;

    /**
     * ������ ��� �� �����
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetLNListBySnilsOut
     * @throws InternalException
     */
    @WebMethod(operationName = "GetLNListBySnils", action = "http://www.fss.ru/integration/ws/eln/mo/getLNListBySnils/v01")
    @WebResult(name = "getLNListBySnilsResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public FileOperationsLnUserGetLNListBySnilsOut getLNListBySnils(
        @WebParam(name = "getLNListBySnilsRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        GetLNListBySnilsRequest request)
        throws InternalException
    ;

    /**
     * ������ ����� �������� ������� ���
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetExistingLNNumRangeOut
     * @throws InternalException
     */
    @WebMethod(operationName = "GetExistingLNNumRange", action = "http://www.fss.ru/integration/ws/eln/mo/getExistingLNNumRange/v01")
    @WebResult(name = "getExistingLNNumRangeResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public FileOperationsLnUserGetExistingLNNumRangeOut getExistingLNNumRange(
        @WebParam(name = "getExistingLNNumRangeRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        GetExistingLNNumRangeRequest request)
        throws InternalException
    ;

    /**
     * ������ ������ ���
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetNewLNNumOut
     * @throws InternalException
     */
    @WebMethod(operationName = "GetNewLNNum", action = "http://www.fss.ru/integration/ws/eln/mo/getNewLNNum/v01")
    @WebResult(name = "getNewLNNumResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public FileOperationsLnUserGetNewLNNumOut getNewLNNum(
        @WebParam(name = "getNewLNNumRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        GetNewLNNumRequest request)
        throws InternalException
    ;

    /**
     * ������ ������� ������� ���
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetNewLNNumRangeOut
     * @throws InternalException
     */
    @WebMethod(operationName = "GetNewLNNumRange", action = "http://www.fss.ru/integration/ws/eln/mo/getNewLNNumRange/v01")
    @WebResult(name = "getNewLNNumRangeResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public FileOperationsLnUserGetNewLNNumRangeOut getNewLNNumRange(
        @WebParam(name = "getNewLNNumRangeRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        GetNewLNNumRangeRequest request)
        throws InternalException
    ;

    /**
     * ������ ������ ���
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.mo.v01.FileOperationsLnUserGetLNDataOut
     * @throws InternalException
     */
    @WebMethod(operationName = "GetLNData", action = "http://www.fss.ru/integration/ws/eln/mo/getLNData/v01")
    @WebResult(name = "getLNDataResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public FileOperationsLnUserGetLNDataOut getLNData(
        @WebParam(name = "getLNDataRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        GetLNDataRequest request)
        throws InternalException;

    /**
     * ������ �� ������������� ���
     * 
     * @param request
     * @return
     *     returns main.java.ru.genereted.v2.types.eln.v01.WSResult
     * @throws InternalException
     */
    @WebMethod(operationName = "DisableLn", action = "http://www.fss.ru/integration/ws/eln/mo/disableLn/v01")
    @WebResult(name = "disableLnResponse", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "response")
    public WSResult disableLn(
        @WebParam(name = "disableLnRequest", targetNamespace = "http://www.fss.ru/integration/types/eln/mo/v01", partName = "request")
        DisableLnRequest request)
        throws InternalException
    ;

}
